# Generated by Django 3.0.5 on 2020-04-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idboleta', models.AutoField(db_column='IdBoleta', primary_key=True, serialize=False)),
                ('fechaboleta', models.DateTimeField(db_column='FechaBoleta')),
                ('subtotalboleta', models.IntegerField(db_column='SubTotalBoleta')),
                ('ivaboleta', models.DecimalField(db_column='IVABoleta', decimal_places=0, max_digits=10)),
                ('totalboleta', models.DecimalField(db_column='TotalBoleta', decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(db_column='IdCategoria', primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(db_column='NombreCategoria', max_length=50)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('iddespacho', models.AutoField(db_column='IdDespacho', primary_key=True, serialize=False)),
                ('fechainicio', models.DateTimeField(db_column='FechaInicio')),
                ('fechatermino', models.DateTimeField(blank=True, db_column='FechaTermino', null=True)),
                ('direcciondestino', models.CharField(db_column='DireccionDestino', max_length=100)),
            ],
            options={
                'db_table': 'despacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadodespacho',
            fields=[
                ('idestadodespacho', models.IntegerField(db_column='IdEstadoDespacho', primary_key=True, serialize=False)),
                ('nombreestadodespacho', models.CharField(db_column='NombreEstadoDespacho', max_length=50)),
            ],
            options={
                'db_table': 'estadodespacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadoordencompra',
            fields=[
                ('idestadooc', models.IntegerField(db_column='IdEstadoOC', primary_key=True, serialize=False)),
                ('nombreestadooc', models.CharField(db_column='NombreEstadoOC', max_length=50)),
            ],
            options={
                'db_table': 'estadoordencompra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadopago',
            fields=[
                ('idestadopago', models.IntegerField(db_column='IdEstadoPago', primary_key=True, serialize=False)),
                ('nombreestadopago', models.CharField(db_column='NombreEstadoPago', max_length=50)),
            ],
            options={
                'db_table': 'estadopago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadoventa',
            fields=[
                ('idestadoventa', models.IntegerField(db_column='IdEstadoVenta', primary_key=True, serialize=False)),
                ('nombreestadoventa', models.CharField(db_column='NombreEstadoVenta', max_length=50)),
            ],
            options={
                'db_table': 'estadoventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idfactura', models.AutoField(db_column='IdFactura', primary_key=True, serialize=False)),
                ('fechafactura', models.DateTimeField(db_column='FechaFactura')),
                ('subtotalfactura', models.IntegerField(db_column='SubTotalFactura')),
                ('ivafactura', models.DecimalField(db_column='IVAFactura', decimal_places=0, max_digits=10)),
                ('totalfactura', models.DecimalField(db_column='TotalFactura', decimal_places=0, max_digits=10)),
                ('rutempresa', models.CharField(db_column='RutEmpresa', max_length=12)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordencompra',
            fields=[
                ('idordencompra', models.AutoField(db_column='IdOrdenCompra', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
            ],
            options={
                'db_table': 'ordencompra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.AutoField(db_column='IdPago', primary_key=True, serialize=False)),
                ('monto', models.IntegerField(db_column='Monto')),
                ('fechapago', models.DateTimeField(db_column='FechaPago')),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.BigIntegerField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(db_column='NombreProducto', max_length=100)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=500)),
                ('stock', models.IntegerField(db_column='Stock')),
                ('stockcritico', models.IntegerField(db_column='StockCritico')),
                ('precio', models.IntegerField(db_column='Precio')),
                ('marca', models.CharField(db_column='Marca', max_length=50)),
                ('fechavencimiento', models.DateTimeField(blank=True, db_column='FechaVencimiento', null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.AutoField(db_column='IdProveedor', primary_key=True, serialize=False)),
                ('rutproveedor', models.CharField(db_column='RutProveedor', max_length=12)),
                ('nombreproveedor', models.CharField(db_column='NombreProveedor', max_length=100)),
                ('telefono', models.IntegerField(db_column='Telefono')),
                ('correo', models.CharField(db_column='Correo', max_length=100)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.IntegerField(db_column='IdRol', primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(db_column='NombreRol', max_length=50)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('idrubro', models.IntegerField(db_column='IdRubro', primary_key=True, serialize=False)),
                ('nombrerubro', models.CharField(db_column='NombreRubro', max_length=150)),
            ],
            options={
                'db_table': 'rubro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('idsubcategoria', models.AutoField(db_column='IdSubCategoria', primary_key=True, serialize=False)),
                ('nombresubcategoria', models.CharField(db_column='NombreSubCategoria', max_length=50)),
            ],
            options={
                'db_table': 'subcategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipopago',
            fields=[
                ('idtipopago', models.IntegerField(db_column='IdTipoPago', primary_key=True, serialize=False)),
                ('nombretipopago', models.CharField(db_column='NombreTipoPago', max_length=50)),
            ],
            options={
                'db_table': 'tipopago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, db_column='Rut', max_length=12, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=50, null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(db_column='IdVenta', primary_key=True, serialize=False)),
                ('fechaventa', models.DateTimeField(db_column='FechaVenta')),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdencompraProducto',
            fields=[
                ('idproducto', models.OneToOneField(db_column='IdProducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fermeApp.Producto')),
                ('cantidadoc', models.IntegerField(db_column='CantidadOC')),
            ],
            options={
                'db_table': 'ordencompra_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('idproducto', models.OneToOneField(db_column='IdProducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fermeApp.Producto')),
                ('cantidadproducto', models.IntegerField(db_column='CantidadProducto')),
            ],
            options={
                'db_table': 'venta_producto',
                'managed': False,
            },
        ),
    ]
